name: flutter_facebook_wrapper
description: Facebook SDK wrapper
version: 0.0.3
author: Innim
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: ru.innim.flutter_facebook_wrapper
        pluginClass: FlutterFacebookWrapperPlugin
